micronaut:
  application:
    name: short-url-generator
  server:
    port: 8080
    cors:
      enabled: true
    netty:
      log-level: ERROR

---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      logout:
        enabled: false
      oauth:
        enabled: false
    token:
      propagation:
        enabled: true
        service-id-regex: "analytics-service"
        uri-regex: ".*"
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:ThisIsHighlySensitiveInformation}"
---
micronaut:
  metrics:
    enabled: true
---
zookeeper:
  url: zookeeper:2181
---
redis:
  url: redis://redis-cache:6379
---
url-lifetime-in-secs:
  anonymous: 60
  authenticated: 120
---

mysql:
  url: jdbc:mysql://db:3306/short_url_generator
  user: root
  password: unsecured

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
