micronaut:
  application:
    name: api-gateway
  server:
    port: 8080
    cors:
      enabled: true
    netty:
      log-level: ERROR

---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      logout:
        enabled: false
      oauth:
        enabled: false
    token:
      propagation:
        enabled: true
        service-id-regex: "short-url-generator"
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:ThisIsHighlySensitiveInformation}"
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
