micronaut:
  application:
    name: user-service
  server:
    port: 8080
    cors:
      enabled: true
    netty:
      log-level: ERROR

---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:ThisIsHighlySensitiveInformation}"
---

micronaut:
  metrics:
    enabled: true
    export:
      graphite:
        enabled: true
        host: graphite
---

mysql:
  url: jdbc:mysql://userdb:3306/user_db
  user: root
  password: unsecured

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
