micronaut:
  application:
    name: id-gen-service
  server:
    port: 8080
    cors:
      enabled: true
    netty:
      log-level: ERROR

---
endpoints:
  prometheus:
    sensitive: false
---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
---
zookeeper:
  url: zookeeper:2181

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
