micronaut:
  application:
    name: id-gen-service
  server:
    port: 8080
    cors:
      enabled: true
    netty:
      log-level: ERROR

---
micronaut:
  metrics:
    enabled: true
    export:
      graphite:
        enabled: true
        host: graphite
---
zookeeper:
  url: zookeeper:2181

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:consul}:${CONSUL_PORT:8500}"
